### ISSUE TITLE
AVR-513 AC not imported correctly

### ISSUE THREAD

**Issue by gortogg** [avrae/avrae#1007]
**Describe the bug**
The AC of this character https://www.dndbeyond.com/profile/Gortogg/characters/25101973 is not imported correctly. It looks that the natural armor of Lizardfolk isn't calculated correctly in avrae, and isn't imported from beyond.

**Severity**
Medium (minor functional impact)

**Context**
I imported the character sheet in the bot, and the AC wasn't correctly displayed nor used in the calculations.

**To Reproduce**
1. import the character sheet https://www.dndbeyond.com/profile/Gortogg/characters/25101973
2. display it 
3. see error : read the wrong AC (15) instead of 17.

**Expected behavior**
I expected the AC from DnD beyond to be displayed

**Comment by Croebh** [comment]
![image](https://user-images.githubusercontent.com/5848891/77503517-62e05080-6e23-11ea-9458-77dfea96d714.png)
Seems to upload fine for me O.o

**Comment by gortogg** [comment]
Yup. I tryed to un-equip the armor and now it is imported correctly. I believe that the armor has some kind of priority ?
