### ISSUE TITLE
AVR-519 Homebrew spell incorrectly apply saves on attack hit

### ISSUE THREAD

**Issue by psenne** [avrae/avrae#1021]
Summary:
This applies when using a homebrew attack (melee or spell) that requires a save "on hit". When the attack has advantage or scores a critical hit, not only will the attack get two rolls, but so will the target's save rolls against the effect.

Details:
I created a custom spell (Sickening Blast) which is just Eldritch Blast with some extra poison damage attached and a poisoned condition on hit. The target gets to make a saving throw against the condition, but only on a successful hit. The spell works beautifully when standard rolls are used. The bug is occurring when the attack roll either crits or is made with advantage. The attack and damage dice are rolled twice, as it should, but then so is the target's save. The target's should only get one save, because there was only one successful hit. I have a screenshot attached of an example. I have also attached the json that I used for it, in case I didn't do it correctly. 

[sickening_blast.txt](https://github.com/avrae/avrae/files/4434172/sickening_blast.txt)

![image](https://user-images.githubusercontent.com/11689300/78502404-118f6580-772f-11ea-91b3-b97850bd5547.png)

**Comment by Croebh** [comment]
This is a current limitation in the automation system. The workaround is to use `adv1` instead of `adv`

**Comment by psenne** [comment]
Groovy. What about crits?

**Comment by psenne** [comment]
actually, I just tested with adv1 and when it crits, the save isn't affected either. so that only leaves crits on a non-advantage roll. good enough for me. thanks for the help.

**Comment by Croebh** [comment]
Whats wrong with the crits? Also, if you don't want the damage doubled up, it you can put the poison damage in the same Damage field as the force (`1d10[force]+{charismaMod}[force]+2d6[poison]`)

**Comment by psenne** [comment]
actually, crits (when not using adv) work just fine. So adv1 solves everything. Thanks for all the help.
