### ISSUE TITLE
AVR-124 Avrae doesn't correctly import Dicecloud IF statements

### ISSUE THREAD

**Issue by kaczkara** [avrae/avrae#109]
If and 'if' is used in a formula field on Dicecloud, Avrae will not properly evaluate the value.

**Comment by Croebh** [comment]
https://discordapp.com/channels/269275778867396608/370001186385952770/370257829342347264

**Comment by kaczkara** [comment]
I don't understand how that's an issue.  It appears that Avrae processes the value as a string and then parses/evaluates.  At this point, why would keywords matter?

**Comment by mommothazaz123** [comment]
Avrae evaluates Dicecloud scripting by parsing it as Python (using the abstract syntax tree compiler); attempting to parse a string with `if` used as a function throws a SyntaxError (as expected).

[Relevant Code](https://github.com/avrae/avrae/blob/master/cogs5e/sheets/dicecloud.py#L594)

**Comment by kaczkara** [comment]
Seems like it'd be rather easy to improve this code by rewriting 'if's as ternary ops/inline ifs, then treating it as Python.  

But doesn't this potentially open up security vulnerabilities, since you aren't checking for malicious code?

**Comment by Croebh** [comment]
I mean, if it's 'rather easy', then perhaps make a pull request?

**Comment by mommothazaz123** [comment]
Nothing stops the user from writing their statements as ternary ops in Dicecloud (Dicecloud's math.js won't parse it correctly, though).

The evaluator does not use Python's built in `eval()` - it only uses Python syntax to parse the code into AST nodes, which allows me low-level control over exactly what users can and cannot execute in their code (in the case of Dicecloud's evaluator, they're limited to a namespace with only `max`, `ceil`, etc).

As Croebh said, I'd be happy to review a PR.

**Comment by kaczkara** [comment]
Thank you @mommothazaz123 for answering my questions.   I am curious about adding in this feature myself, however my schedule is quite full and I can't take on yet another project.  My only hope was to have a conversation about this, especially considering the lack of documentation regarding the bot's limitations.   I'd suggest adding documentation on the webpage or in the bots help commands to make this particular limitation clear, as its an extremely useful feature of Dicecloud that you don't support.

**Comment by kaczkara** [comment]
Although, I did just have an idea that might make the whole thing easier as far as implementation goes.  If you do a find replace on the string given by discord to replace any 'if' with a custom function, then you could pass it through the AST nodes no problem.  A very small change less than 10 lines of code.

```python
def if_func(cond, true_val, false_val):
    if cond:
        return true_val
    else:
        return false_val

def rewrite_if(str_val):
    str_val = str_val.replace('if', 'if_func')
    return str_val
```

**Comment by mommothazaz123** [comment]
This limitation is documented on the [Avrae Support Discord](https://support.avrae.io). Seeing as it's not documented in Dicecloud docs (to my knowledge), this is technically an edge case (which if I were to document every one, I'd have no time to actually develop the bot).

**Comment by kaczkara** [comment]
I understand the concern with words containing 'if' in the middle, however as far as I can tell Dicecloud does not support custom variables and none of the current variables contain 'if' anywhere in them.  I've been using this [google sheet](https://docs.google.com/spreadsheets/d/1UfZ9e9Z9XFiZ7uapyDxrh9UskZSmPGa-nWr7mCqzevw/edit#gid=0 ) as a reference for writing Dicecloud equations.
