### ISSUE TITLE
AVR-566 Short Rest Not Resetting Warlock Spell Slots

### ISSUE THREAD

**Issue by Inxanity1** [avrae/avrae#1099]
**Describe the bug**
When doing !g sr, warlock spell slots are not reset. They do reset on long rest (!g lr)

**Severity**
High

**Context**
!g sr

**To Reproduce**
1. Load Warlock character to Avrae
2. Cast a spell (!cast <spell name>)
3. Take a short rest (!g sr)

**Expected behavior**
Give back a used Spell Slot

**Screenshots**
![AvraeWarlockSpellSlot](https://user-images.githubusercontent.com/65743487/82617966-8c4cfc80-9b86-11ea-948c-9540d1d0323f.png)

**Comment by Croebh** [comment]
There is a character setting, `!csettings srslots true`, that will reset all your slots on a short rest. The key word there being 'all', so it's not going to work well on a multiclassed warlock.
