### ISSUE TITLE
AVR-572 Roll Parser Unsanitized for d in comments

### ISSUE THREAD

**Issue by villarrealas** [avrae/avrae#1109]
**Describe the bug**
The standard roll parser `!r` is unable to properly handle the letter d. This does not seem to show up in other comment ambiguities that were addressed and can likely be sourced back to changes in https://github.com/avrae/avrae/issues/1079

Error returned is:
```Error in roll: Unexpected input on line 1, col 9: expected INTEGER, got e```

I suspect the issue is the fragment grabber sees the lower case d as the start of a dice sequence.

**Severity**
Low

**Context**
!r 1d20+6 dex save

**To Reproduce**
As above with Discord bot.

**Expected behavior**
I would expect the dice to roll 1d20, add six, and return "dex save: 1d20+6".

**Comment by Infinidoge** [comment]
The discord link appears to be inaccessible

**Comment by villarrealas** [comment]
Fixed with actual link and not me accidentally copying the Discord message link that this was discussed in!

**Comment by Infinidoge** [comment]
I believe this bug report is invalid as this has actually already been fixed, it just hasn't been deployed to Production yet. If you check the Nightly build on the dev server, it works properly:
![image](https://user-images.githubusercontent.com/22727114/83218005-08bd7d80-a13b-11ea-98c5-582f48bf7860.png)

**Comment by villarrealas** [comment]
Agreed - I was not checking the nightly build. I'll close this out!
