### ISSUE TITLE
AVR-619 catch err() and commit changes, you dummy

### ISSUE THREAD

**Issue by RCarretta** [avrae/avrae#1195]
**Describe the bug**
When setting a cvar it appears to be set in a cache of sorts. If the script exits with err() shortly after, the cvar will briefly appear to be set and then refresh into nonexistence. 

**Severity**
Medium - In a working script I don't believe this should have any practical effect, but in a broken one it can severely hamper troubleshooting (and is confusing behavior when evaluating a script with errors)

**Context**
Anything with set_cvar, set_uvar, set_cvar_nx, set_uvar_nx, etc. followed by err()

**To Reproduce**
```
!test {{set_cvar("foo","bar")}}
{{f' -f "1:{foo}"'}}
{{f' -f "2:{foo}"'}}
{{err("baz")}}

!cvar foo
!cvar
(pause)
!cvar foo
!cvar
```

**Expected behavior**
Any set values should be committed on err()

**Screenshots**
![image](https://user-images.githubusercontent.com/626446/89750666-c5a85080-da81-11ea-935f-d5fe7be2946a.png)

**Additional context**
https://discordapp.com/channels/269275778867396608/666401385335750666/741597720585961562

**Comment by mommothazaz123** [comment]
For the record, I asked for this issue to be titled this 😛
