### ISSUE TITLE
AFR-600 Allow Users to Enter Commands and Run them as if Entered by Another User

### ISSUE THREAD

**Issue by Zed2XS** [avrae/avrae#1201]
**Who would use it:**

Any user or perhaps only privileged users.

**What part of the bot?**

Unsure.  A command parameter would be needed to override who to issue the command as.

If you mean which command would be affected, potentially all of them.

**How would it work?**

When a user adds the parameter along with a Discord nick or user name Avrae would substitute the user who issued the command with the name of the user in the parameter for most cases.   It should continue to send any prompts to the original user who issued the command though.

If I issue a command as if I was user X I would want any prompts for additional info to come to me to respond to and not sent to user X.

*Example: -as [nick | user name]*

**Why should this be added?**

As a DM it would be nice to be able to perform secret checks on other player's characters.  Currently I have to import every players character sheet and switch characters every time I want to do this.  If I could run a command like !desc -as [nick] to see the details of that user's current character that would be so much easier.

In addition it would allow someone who is an experienced Avrae user to issue commands for players who do not understand or do not want to use the bot.

It would also allow the DM to take a turn as a player who is away from the keyboard during combat rather than wait for them to return or take that character's turn manually (rolling for attack, check the opponents AC, rolling for damage and then modifying the opponents hit points in Avrae manually).

**Additional context**

In addition this could be the first step to allowing webhooks and Discord bots to communicate with and issue commands through Avrae on behalf of a user.  Avrae currently seems to ignore commands entered by bots, so that would be another change needed to make that happen.  With those two features in place it would be possible to integrate Avrae with the D&D Beyond  character sheet or any other alternative interface.

Apart from the creation of some sort of API, this seems like the simplest way to create an alternative interface for Avrae.

> Note - Croebh#5603
> 
> this seems incredibly dangerous from a data point of view

> Note - GitHub - mommothazaz123
> 
> Echoing the above. This could potentially allow other users to perform destructive actions on another's behalf, which is a can of worms best left unopened. At the moment, there are no plans to implement such an interface.

> Downvote - Kortar#9227

> Downvote - Lathaon#6649

> Downvote - R to the Ichie#6193

Votes: +0 / -3

**Comment by mommothazaz123** [comment]
Echoing the above. This could potentially allow other users to perform destructive actions on another's behalf, which is a can of worms best left unopened. At the moment, there are no plans to implement such an interface.
