### ISSUE TITLE
AVR-630 Bonus spell damage is not added

### ISSUE THREAD

**Issue by geransmith** [avrae/avrae#1215]
**Describe the bug**
When casting my Eldritch Blast via Avrae, the bonus spell damage is not being added.

**Severity**
Medium (minor functional impact)

**Context**
!cast Eldritch Blast

**To Reproduce**
1. Have a with Eldritch Blast and Agonizing Blast (or possibly another spell with bonus damage)
2. Execute "!cast Eldritch Blast"
3. Observe that the spell is cast, but the bonus spell damage is not applied

**Expected behavior**
The additional CHA damage from Agonizing Blast is applied.

**Screenshots**
Output of the command:
![image](https://user-images.githubusercontent.com/8031619/90984753-e6fe4780-e52b-11ea-9ec0-7fdc740f3566.png)

Screenshot of my character with the bonus Eldritch Blast damage:
![image](https://user-images.githubusercontent.com/8031619/90984765-04cbac80-e52c-11ea-9caa-474f25dbbe0b.png)

**Comment by Infinidoge** [comment]
This is working as intended.
Avrae does not import data for any class features, and thus it is up to the user to add the damage themselves

A simple way to do so is to use a snippet, such as
```
!snippet agonizing -d <charismaMod>
```
Or to create a homebrew version of the spell with the added damage.
The latter will require the spell to be renamed on the sheet, however.

**Comment by geransmith** [comment]
Ahh, good to know. The way I read it was that it would import that. Thanks for the tip!
