### ISSUE TITLE
AVR-640 What's the policy on outside contributions?

### ISSUE THREAD

**Issue by adamcataldo** [avrae/avrae#1238]
Hi,

I'm interested in contributing to avrae, but didn't see a contributing.md file or anything like that, and I'm not sure if your open to contributions from outside D&D Beyond or not. For what it's worth, I'd be happy to take on some starter bugs to get familiar with the code base, style rules, etc. (I'd also be happy to create a contributing.md file, so outside contributors know what to expect going forward.) My interest is mostly as a player, who would like to see some of the currently open issues solved, and wouldn't mind helping.

**Comment by Infinidoge** [comment]
Hey, and welcome to Avrae! Nice to see other people wishing to contribute.

We usually communicate on the support Discord server [here](https://support.avrae.io)

As for contributing, you are welcome to submit pull requests at your leisure, and the maintainers at D&DBeyond will review it. (Pull requests have a template go fill in for the respective changes, such as what bug report or feature request it addresses, and so on.)

There isnt really a concrete policy for contributing, but if you have any specific questions you can feel free to ask in the Discord server linked above.

**Comment by adamcataldo** [comment]
Got it; thanks!
