### ISSUE TITLE
AVR-646 Sorcerer Can't Use Spells

### ISSUE THREAD

**Issue by caddyshack327** [avrae/avrae#1258]
**Describe the bug**
I have a Sorcerer on my 5E game who can't cast Chromatic Orb or Chaos Bolt. I have made a separate sorcerer and tried these spells and they work for my character but she can't use it on her character and it's very frustrating.

**Severity**
Low

**Context**
!cast "Chaos Bolt"

**Expected behavior**
When user types "!cast "Chaos Bolt"" it should cast Chaos Bolt but it doesn't work for one user on my server.

**Comment by mommothazaz123** [comment]
Make sure your player's D&D Beyond account is linked to their Discord account here: https://www.dndbeyond.com/account

You can check the status of the account link by running `!ddb`.
