### ISSUE TITLE
AVR-676 Can create a counter with no maximum that resets to 0 on long rest using !cc, but not <drac2>

### ISSUE THREAD

**Issue by TonySamuels** [avrae/avrae#1354]
**Describe the bug**
I want a counter with no maximum that resets to 0 on long rest.

I used to do this by setting a maximum of 0 and using negative numbers:
```
create_cc(dc_name, maxVal=0, reset="long")
```

With a recent patch, this now fails:
```
create_cc_nx(dc_name, maxVal=0, reset="long")
^
Traceback (most recent call last):
cogs5e.models.errors.InvalidArgument: Max value cannot be 0.
```

Notably the old behaviour still works for anyone who has an existing cc, so it doesn't seem to be an intrinsic limitation, just one applied at creation.

I have tried to use the new reset_to field, however it still requires a maximum, which I do not want to set:
```
Error on line 8, col 0:
character().create_cc_nx(dc_name, reset_to=0, reset="long")
^
Traceback (most recent call last):
cogs5e.models.errors.InvalidArgument: Reset passed but no maximum passed.
```

However, I *can* implement this with the new reset_to field if I use !cc:
```
!cc create "testing" -min 0 -resetto 0 -reset long
```

**Severity**
Medium (minor functional impact)

**Context**
```
!alias vz <drac2>
character().create_cc_nx("Test CC, please ignore", reset_to=0, reset="long")
</drac2>
```

**To Reproduce**
Run the alias from Context.

**Expected behavior**
A custom counter should be created that has no maximum value, and resets to a given value on long rest.

**Screenshots**
I don't think these are required, but can provide on request.

**Additional context**
Confirmed on the Avrae discord channel, to (hopefully) verify I am not just doing something silly. There's probably no new information there, but it seems harmless to include.
Conversation in #alias-help: https://discord.com/channels/269275778867396608/666401385335750666/774820898871574560
Conversation in #alias-testing: https://discord.com/channels/269275778867396608/677592300313903105/774825420674564127

> Can Reproduce - TheReverendB#1377

Verification: 1

**Comment by mommothazaz123** [comment]
Mahkasad is correct - `create_cc` expects a string, and the error stems from the fact that `0` is falsy. I'll add an internal cast to string for this, though, since passing an `int` should also be supported.
