### ISSUE TITLE
AFR-744 Custom Character Sheets

### ISSUE THREAD

**Issue by HowToGamingg** [avrae/avrae#1446]
My newest campaign is going to be ultra realistic and require me to make custom character sheets for things like individual limb damage, curses, armor combinations, ect. I tried to use google sheets to see if it would work with Avrae and the custom sheet but it didn't.

I believe there are a lot of people who could use this, there are a lot of DnD players who want realism but it can be hard to do everything over discord with no bot to help and could get confusing.

Sheet Manager

I dont know coding so I wouldn't know how it works, however I would be more than happy to send a copy of my character sheet for everyone to base it off of.

Even if not everyone or just a niche of people would use it, having more functionality with Avrae would do nothing but help, DnD is all about using your imagination and sadly, when it comes to playing via discord, our imaginations have been limited due to the software, bots, ect that we have to use.

Here is the general idea for my new sheet, thank you for taking the time to read my request.
[Windfold Custom Character Sheet.docx](https://github.com/avrae/avrae/files/6031793/Windfold.Custom.Character.Sheet.docx)

> Downvote - Dr Turtle#1771

> Downvote - Hopop#6751

> Downvote - spamandtuna#9657

> Downvote - Riptidecord#7191

> Note - GitHub - hopop201
> 
> There would be way to much work to make Avrae able to read a different different sheet that does not have information set out in specific places like exist character creator websites. Telling Avrae to read stuff that is not in base D&D as well is not a good idea. If you want to track a bunch of homebrew stuff, you could probably uses aliases and counters to accomplish that. I would also say that discord only limits your imagination as much as you let it.

> Downvote - Lathaon#6649

> Downvote - bobschnitzenheimer#2159

Votes: +0 / -6

**Comment by hopop201** [comment]
There would be way to much work to make Avrae able to read a different different sheet that does not have information set out in specific places like exist character creator websites. Telling Avrae to read stuff that is not in base D&D as well is not a good idea. If you want to track a bunch of homebrew stuff, you could probably uses aliases and counters to accomplish that. I would also say that discord only limits your imagination as much as you let it.

**Comment by mommothazaz123** [comment]
Thanks for the request! In the future, please come check in at the [Avrae Development Discord](https://support.avrae.io) before opening a feature request.

Avrae was designed around core D&D 5e mechanics, and implementing support for homebrew sheets is not feasible at this time.
