### ISSUE TITLE
AVR-760 Imported Spells throw a TypeError

### ISSUE THREAD

**Issue by mclemente** [avrae/avrae#1476]
**Describe the bug**
If I import a spell through JSON, Avrae creates the spell, but throws `TypeError: '>' not supported between instances of 'str' and 'int'`, if I create the exact same spell, it works.

**Severity**
High

**Context**
`!tome TOMENAME`
`!spell SPELLNAME`

**To Reproduce**
1. Import the following spell:
```json
{"name":"Spellname","level":"","school":"","classes":"","subclasses":"","casttime":"","range":"","components":{"verbal":false,"somatic":false,"material":""},"duration":"","ritual":false,"description":"A","higherlevels":"","concentration":false,"automation":[]}
```
2. Use `!spell Spellname`
3. Delete `Spellname`
4. Create a cantrip named `Spellname` with the description `A`.
5. Use `!spell Spellname`
6. Export `Spellname` and compare its JSON with the one above.

**Comment by 1drturtle** [comment]
I *believe* this is due to the `level` field in the automation being blank, where it should be `0`.

**Comment by mclemente** [comment]
That fixed it, but some sanitization could be added to avoid the JSON being accepted like that. I couldn't tell at all what was doing it.
