### ISSUE TITLE
AVR-761 Attacking with a rock uses a DEX save instead of STR

### ISSUE THREAD

**Issue by abrudner** [avrae/avrae#1477]
**Describe the bug**
When using a ranged attack with a rock, Avrae rolls a DEX save when the effect says it should make a STR save.

**Severity**
Medium (minor functional impact)

**Context**
> !i attack Rock -t <character>

**To Reproduce**
1. Have big ole stone giant. (or other rock throwing creature)
2. Have it be the giant's turn.
3. Let your bard piss it off enough that it wants to throw a rock at it.
4. Throw rock.
5. See Screenshot.

**Expected behavior**
Avrae should make a STR saving throw for the affected character instead of a DEX saving throw.

**Screenshots**
![image](https://user-images.githubusercontent.com/13434120/112251380-bfd23a80-8c20-11eb-842c-fc5d2ef1e57a.png)

**Additional Context**
Used attack instead of mattack when on the monster's turn.

> Can Reproduce - Dr Turtle#1771

Verification: 1

**Comment by Croebh** [comment]
Fixed the automation for the Stone Giant throw (Likely won't be live yet when you read this), and did a search through and didn't see any others with the issue. 

Are you aware of any other monsters with incorrect saves or other issues like this? If so, please let me know so I can fix them :-)

**Comment by abrudner** [comment]
No but I'll be looking out for them. Where was this change made? I was looking for it last night.

**Comment by Croebh** [comment]
The automation info is kept in a private repo due to copyright and licensing stuff

**Comment by abrudner** [comment]
Got it, makes sense. Thanks!

**Comment by zhudotexe** [comment]
Fix will be rolled out in the next data update.
