### ISSUE TITLE
AVR-816 Low rolls

### ISSUE THREAD

**Issue by Goury** [avrae/avrae#1597]
**Describe the bug**
After not being used for some time, Avrae rolls 1 more often than not

**Severity**
High

**Context**
Any roll taken after Avrae not being called for some time (feels like 5-10 minutes) have ~30% chance to return 1

**To Reproduce**
1. wait
2. roll
3. get 1

**Expected behavior**
Fair random roll

**Screenshots**
![Снимок экрана от 2021-08-01 19-09-00](https://user-images.githubusercontent.com/1081221/127777797-cf23d617-f668-4671-84ad-3c67198acbdb.png)

**Additional context**
This is highly annoying and also makes my games feel unfair.

**Comment by hopop201** [comment]
That is not a bug, it is just how rng works. The rolls that you see are barely a fraction of all the rolls that Avrae does.

**Comment by Goury** [comment]
@hopop201 this is not rng, this is a bug.
Regardless of being fraction or not, having 30 out of 100 d20 rolls to roll 1 is not right.

**Comment by Goury** [comment]
WTF did you close the issue?
The issue is present, stop ignoring it.

**Comment by hopop201** [comment]
> @hopop201 this is not rng, this is a bug.
> Regardless of being fraction or not, having 30 out of 100 d20 rolls to roll 1 is not right.

It is not out of 100, it is more like out of 100000, if not more. And again, that is how randomness works.

**Comment by zhudotexe** [comment]
You are welcome to run your own analysis of the dice rolling library. https://github.com/avrae/d20
