### ISSUE TITLE
AVR-842 Dicecloud import throwing error: "equal is not defined"

### ISSUE THREAD

**Issue by christhekeele** [avrae/avrae#1636]
**Describe the bug**
I've followed the installation guide as of 2021-10-06. I then follow the dicecloud guide with a public character sheet. When I try to import it, I receive the error message:

`Error loading character: equal is not defined`

**Severity**
`High` (a broken feature, major functional impact)

**Context**

The character sheet I am importing is publicly available for inspection.

The command I run is

`!dicecloud https://dicecloud.com/character/oQpMssudeYYFyx4uy/Auriel`

This also occurs with the `!import` variant. Screenshot included below.

**To Reproduce**
1. Add Avrae to a discord server
2. Run command as described above
3. See error

**Expected behavior**
I'd expect character import from dicecloud to succeed. Beyond that I am not sure what the desired result would be, as this is the only character I have to import.

**Screenshots**

![Screen Shot 2021-10-06 at 11 09 06 AM](https://user-images.githubusercontent.com/1406220/136259334-5d345b8e-a66d-4552-a213-28521fc4785c.png)

**Additional context**

The character sheet I am using makes heavy use of dicecloud's formula features, which may be the source of the issue.

**Comment by christhekeele** [comment]
> Note - TheReverendB#1377
> 
> I recommend you come to the Avrae server where someone can likely assist with your formulas. https://discord.gg/93D4CqXc

I have joined, but it appears I don't have posting permissions yet 😂 I lost track of the onboarding message, maybe it's just a matter of time.

**Comment by Croebh** [comment]
I don't think there is any documentation on that no. Ceil/floor/if/min/max should all work though, not entirely sure about others. I'll see about looking into this more

**Comment by christhekeele** [comment]
@Croebh I have both a confirmed email address and phone number for my account. Probably shouldn't pollute the bug tix here though, I'm `RawSugarRage#7042` on discord. :)

**Comment by christhekeele** [comment]
Updated: swapping out `equal(value1, value2)` for `value1 == value2` did the trick. I am also using `smaller` and `largeEq` but apparently off the import path. I'll close this out and submit a feature request for supporting these mathjax functions.

**Comment by christhekeele** [comment]
Thanks for all the instantaneous support, @Croebh ! 
💞❤️🧡💛💚💙💜💖💜💙💚🧡💛❤️💘
