### ISSUE TITLE
AVR-847 json_load() Error

### ISSUE THREAD

**Issue by ShadowWyzard** [avrae/avrae#1642]
**Describe the bug**
Potentially me just not having a clue what I'm doing.
I was messing around with random commands and tried to use json_load(), but I ended up getting an error saying that I used 3 positional arguments when it only takes two.
**Severity**
Trivial
**Context**
!test <drac 2>
json_load("Numbers",{"One":"Two"})</drac 2>
**To Reproduce**
Simply use the same command as above. I tried a few different variations of different things, including pasting an entire json list exported from CritterDB, but it just told me the same thing or gave me a syntax error instead.

**Expected behavior**
I don't really know what should have happened, but I expected some form of list created from translating json to python.

**Comment by zhudotexe** [comment]
Hi there! This sounds like you're having trouble with part of the Draconic API, which is not an issue in the bot code. For more assistance and to collaborate with other Draconic developers, please join the Avrae Development discord at https://support.avrae.io.
