### ISSUE TITLE
AVR-876 Rerolling spell doesn't take extra slots

### ISSUE THREAD

**Issue by AmbarishGK** [avrae/avrae#1690]
**Description**
When a spell is cast with a reroll it doesn't take extra slots. If this is intended, I will close this issue.

**Severity**
Medium

**Context**
I tried to cast haste spell using reroll 10 times. Only 1 spell slot was used even though the spell was cast ten times.

**To Reproduce**
1. Go to the Bot
2. Type any spell `!cast haste -rr 10`

**Expected behavior**
I think each iteration should take up one slot unless ignore `-i` is used

**Screenshots**
`!cast haste -rr 10`

![avrae](https://user-images.githubusercontent.com/23191860/148962275-0a4d5427-b07f-4e26-835a-8eb391a7a001.png)

**Comment by hopop201** [comment]
This is completely not a bug and intended. Reroll is for spells with multiple attacks/hits like Magic Missile, Scorching Ray and Eldritch Blast. I don't know why you would be trying to reroll Haste anyway as it is a concentration spell and it doesn't actually have any rolls associated with it. Also in the future please submit any possible bugs to the bug discussion channel on the Avrae dev discord before submitting said bug.

**Comment by AmbarishGK** [comment]
> This is completely not a bug and intended. Reroll is for spells with multiple attacks/hits like Magic Missile, Scorching Ray and Eldritch Blast. I don't know why you would be trying to reroll Haste anyway as it is a concentration spell and it doesn't actually have any rolls associated with it. Also in the future please submit any possible bugs to the bug discussion channel on the Avrae dev discord server before submitting said bug.

Sorry, I was playing around and thought found something. I'll close this issue. Sure, I'll do that from now on. Thanks
