### ISSUE TITLE
AVR-159 Monster Attacks Not Found Bug

### ISSUE THREAD

**Issue by badooga** [avrae/avrae#187]
**What is the bug?**: "No attack with that name found" despite the monster existing and no specific attacks being called (probably something to do with the multi-worded nature of the inputted name; it works fine when only one word is used, such as just `!monster_atk young` or `!monster_atk dragon`).
**Severity**: Low or Medium
**Steps to reproduce**: `!monster_atk young black > any choice` OR `!monster_atk adult red dragon > any choice` OR `!monster_atk blue dragon > any choice`

**Comment by Croebh** [comment]
`![monster_atk|ma|monster_attack] <monster_name> [atk_name=list] [args]`
you need to use "quotes"
when you're searching `!ma young black dragon`
its trying to
`search for young` you choose young black dragon
`search for attack named black`
and `use snippet dragon`

versus `!ma "young black dragon"` 
in which case its searching specifically for that dragon, and defaulting to list

**Comment by badooga** [comment]
I see, thank you. The inconsistency of the results threw me off a bit, but now I understand why it happened that way. Have a great day!
