### ISSUE TITLE
Changing how THP is granted.

### ISSUE THREAD

**Issue by DragooMind** [avrae/avrae#1880]
Making it so that automation granting thp default to keeping the bigger value.

Armor of Agathys and Sybiotic Entity would be noteable exceptions though I think automation would only work in the sense that they would keep replacing thp regardless.

**Comment by zhudotexe** [comment]
Just FYI - the enhancement label you chose here actually marks the issue as an internal note and causes it not to be tracked by our feature request system. Please join the development discord at https://support.avrae.io and submit this through the standard feature request flow instead!
