### ISSUE TITLE
AVR-957 Mage Armor Spell Still not Calculating AC Properly

### ISSUE THREAD

**Issue by tjuju-grimm** [avrae/avrae#1907]
My warlock has both Bracers of Defense and Cloth of the LIghtbringer attuned, yet whenever I cast mage armor I only receive the bonus (+2) from the bracers of defense and not the bonus (+3) from the cloth. My Ac calculation is 13+dex+2 instead of 13+dex+5.

**Severity**
Medium

**Context**
My Warlock had the Eldrich Invocation Armor of Shadows and is attuned to bracers and clothing. 
**To Reproduce**
1. Create a warlock with the mage armor invocation
2. Attune both items
3. cast mage armor
4. Note how the only bonus added comes from the bracers

**Expected behavior**
Since the mage armor simply changes your base armor to 13 (as opposed to 10 with the cloth) the character should be getting the bonus from both the bracers and the clothing.

**Screenshots**

![IMG_0810](https://user-images.githubusercontent.com/124000986/215608492-c5db665b-85d8-4ad9-9abc-e32523c27d5f.jpg)
![IMG_0811 (1)](https://user-images.githubusercontent.com/124000986/215608505-59eeb8d9-0734-4cc2-9462-ea568be34fbb.jpg)
![IMG_0811](https://user-images.githubusercontent.com/124000986/215608516-8bf850a1-b6e6-4e97-a2ae-a140f4fc858d.jpg)

**Comment by Croebh** [comment]
Sorry, its un clear from the screenshots... is this an issue with the Avrae Discord bot, or some VTT?

**Comment by tjuju-grimm** [comment]
apologies posted on the wrong thread

**Comment by Croebh** [comment]
Aye, you appear to be looking for something Pathfinder video game related, as opposed to a Discord bot for playing Dungeons & Dragons haha. Best of luck!
