### ISSUE TITLE
AVR-964 Kraul Warrior's 2 handed spear

### ISSUE THREAD

**Issue by Decidudude** [avrae/avrae#1917]
**Describe the bug**
The Kraul Warrior's 2 handed spear deals 1d6+2 instead of 1d8+2

**Severity**
High

**Context**
!i a 2h or !i aoo KW1 2h or !monattack "kraul warrior" 2h

**To Reproduce**
Perform any of the above comands

**Expected behavior**
1d8+2 damage should've been dealt, not 1d6

**Screenshots**
![image](https://user-images.githubusercontent.com/44578256/224190361-b6b1e447-eaa3-42d5-97e3-cd1d4159f0f4.png)

**Comment by hopop201** [comment]
This bug would go in the automation issues megathread AVR-850 https://github.com/avrae/avrae/issues/1647
It would also help if you joined the discord so we could discuss/confirm this bug and any possible future ones you find.

**Comment by Croebh** [comment]
Fixed in upcoming data update
