### ISSUE TITLE
AVR-1008 Coin problems

### ISSUE THREAD

**Issue by CaptainCOOTS** [avrae/avrae#2062]
When I edit coinage on the Beyond character sheet Avrae does not seem to track those changes. Infact, when I use !game coin to alter coins in Avrae it will overwrite what is on the beyond sheet for coins.

**Severity**
Medium-High?

**To Reproduce**
Really basically I started with 10 gp when i created the character. joined the discord server and updated.
Avrae at this point listed 10 gp.
In the beyond sheet I added 3 cp and back iin Discord I !update the character.  Avrae still showed 10 gp.
I did !g coin -3cp and selected yes to convert
Now both Beyond and Avrae showed 9gp 1ep 4sp 7cp.

**Expected behavior**
I simply expected the !update to repull from the Beyond sheet and adjust the coins in Avrae.

**Comment by 1drturtle** [comment]
Avrae is the source of truth for coin changes.

This means that Avrae will sync to DDB, but DDB will not sync to Avrae. This is intended behavior as of now.

**Comment by CaptainCOOTS** [comment]
> Avrae is the source of truth for coin changes.
> 
> This means that Avrae will sync to DDB, but DDB will not sync to Avrae. This is intended behavior as of now.

But adjust DDB did not update Avrae.  Maybe I'm misunderstanding the subject-object use of the word sync. So Avrae has 1-time Read and all time Write to DDB and DDB cannot write to Avrae?

**Comment by SeanStoves** [comment]
Avrae pulls the coins on initial imports only from DDB from that point on, it becomes the source of truth and DDB will be kept updated to Avrae, but not the other way around. 

This was a decision made when Coins were originally added to Avrae a few years back.
