### ISSUE TITLE
`DDB-031` Import from Beyond does not read spell slots

### ISSUE THREAD

**Issue by EEdLoh** [avrae/avrae#291]
I'm using an Eldritch Knight and I'm currently at lvl 4. This gives me 3 spell slots, but none of them load when I use the !update command for Avrae.

![Beyond spell page for my character](https://user-images.githubusercontent.com/10533085/48989415-bc315600-f0ef-11e8-82c6-1f5abecdccdc.png)

![Discord chat with no slots](https://user-images.githubusercontent.com/10533085/48989508-31049000-f0f0-11e8-8ebb-57e61bd6a402.png)

**Comment by mommothazaz123** [comment]
Can you attach an example sheet?
