### ISSUE TITLE
AVR-212 Dicecloud HP Inconsistency [Master Ticket]

### ISSUE THREAD

**Issue by Foxwells** [avrae/avrae#308]
**What is the bug?:** My character's max HP is 27, but Avrae continually prints 41 as her maximum when I have the Tough feat calculated as (2\*ClericLevel).
**Severity:** Moderate
**Steps to Reproduce:** [Import character sheet](https://dicecloud.com/character/M4RFmdrrZXwdhK62N/Crow), go to Features>Tough, change Hit Points effect from (2\*Level) to (2\*ClericLevel).
**Context:** Brought sheet onto Avrae with `!dicecloud` command. Tested updates by using `!game hp` to view HP.
**Additional Note:** Setting this field as (2\*Level) fixes it. Even if that does, it still adds issue for multiclassers who may get bonus HP from their class specifically (such as Draconic Sorcerer or Immortal Mystic). Or just idiots like me who don't know how to use Dicecloud very much... :p 

NOTE: Repost from [here](https://github.com/avrae/avrae-docs/issues/16). In my defense, that was what I got when I googled "avrae github". Either way, very sorry for the spam. I know how annoying that can be so knowing I did something that dumb isn't too pleasant :grimacing:

**Comment by mommothazaz123** [comment]
Oh boy, this one's back. Reposting the message in the discord server and making this the master ticket, since I don't think it's actually been reported on here yet.

> **Bug Bounty - Dicecloud Import Errors**
> Error: Dicecloud often imports HP (and occasionally spell slots) incorrectly, showing an inconsistency between what avrae shows and Dicecloud shows. 
>
> Despite my best efforts, I cannot reproduce this bug consistently - if someone can PM me steps to **consistently** reproduce this bug, there is now a bounty of $20 cash and a special role on this server on the issue.

**Comment by Foxwells** [comment]
Did a bit of research. Set HP as max for all tested levels as to keep out any extraneous variables.

The difference between my Dicecloud sheet and Avrae is 18 at level 1. This reduces by 2 for each level (so, the difference in hp is 16 for level 2, 14 for level 3, etc), until level 9, where it's even. Then, at level 10, Avrae is *behind* by 2. I haven't tested, but I assume that trend continues.

Honestly, don't know what to make of this... but I figure anything is better than nothing.

My current conclusion is that Avrae is reading `ClericLevel` as 9. `(2*9)[tough]+(4*9)[conMod]+(8*9)[maxHP]` yields 126. That's the calculation for max HP at level 9 for my character. It'd also make sense as to why she starts to fall behind after level 9.

No idea why, though. Still something I need to stare at.

**Comment by mommothazaz123** [comment]
I said "might fix," not "fixes," GitHub :P

**Comment by mommothazaz123** [comment]
taine no stop that
