### ISSUE TITLE
AVR-223 Multiple -d Snippets fail on attack

### ISSUE THREAD

**Issue by Ghandi263** [avrae/avrae#350]
Our campaign has a [Rogue/Ranger](https://www.dndbeyond.com/characters/2160917) that adds all sorts of modifiers to his damage rolls. The two that are apparent from his classes are sneak attack and hunter's mark. Right now he is making his attack, rolling extra damage with "!r" and the DM is manually modifying the damage.

I've been trying to find a way to use snippets to make things easier for him, but I'm running into errors. I made a snippet called *sneak* which == "-d 2d6" and another called *mark* which == "-d d8". I've tried calling an attack like "!a crossbow, hand sneak mark", but the damage roll fails saying that it can't find the appropriate dice to roll; which is also what it does when I write the attack command with the snippets translated, "!a crossbow, hand -d 2d6 -d d8". We could write a third snippet that == "-d 2d6+8" but the number of permutations will increase greatly as any other modifiers come into play.

**Comment by Croebh** [comment]
I suspect this is do the the mark snippet being `d8` instead of `1d8`, testing on the dev server with it being `1d8` caused both snippets to work fine

**Comment by Croebh** [comment]
And as a note, you can use `!a hand` or `!a cross`, it simply needs a unique identifier

**Comment by Ghandi263** [comment]
Yea, he has 2 hand crossbows equipped; so, it's hard to find a unique substring. I use that functionality a lot when changing characters, choosing enemies to attack, etc.

**Comment by Croebh** [comment]
Fair. But yeah, if you were to change the mark snippet to specify the number of dice, it should work fine

**Comment by Ghandi263** [comment]
Yep. You're right. Just tested it out. Thanks for your help.
