### ISSUE TITLE
AFR-245 Use the "Appearance" to describe DDB characters if available

### ISSUE THREAD

**Issue by chrisramakers** [avrae/avrae#419]
dndbeyond has an appearance property on sheets which allows for far greater detail when providing a description with `!desc`. Right now the output uses the Characteristics which results in a weird text like below:

> Granbek Gurglegrog is a level 3 Human Barbarian. They are 37 years old, 5ft 7in (170cm) tall, and appears to weigh about 188. They have brown eyes, dark brown hair, and dark skin.

If you would have used the "Appearance" property this would have been used in my case:

> Granbek stands 1m82 tall which is rather tall for his tribe (Nar people are known for their small yet muscular stature).  He has a dark skin tone and wears his dark brown hair in a ponytail with an undercut shave. He has dark brown eyes and thick brushy eyebrows. He proudly wears blue tribal tattoos that range from his face across his chest to his waist and legs.

**Comment by mommothazaz123** [comment]
Can you attach an example sheet?

**Comment by chrisramakers** [comment]
Sure, here you go: https://ddb.ac/characters/4971396/tCG12h
