### ISSUE TITLE
AFR-278 Migrate to discord.py rewrite

### ISSUE THREAD

**Issue by mommothazaz123** [avrae/avrae#472]
- [x] update dependencies
- [x] migrate all bot.say, bot.send_message, snowflakes
    - [x] cogsmisc.adminUtils
    - [x] cogsmisc.core
    - [x] cogsmisc.permissions
    - [x] cogsmisc.publicity
    - [x] cogsmisc.repl
    - [x] cogsmisc.stats
    - [x] utils.help
    - [x] cogs5e.dice
    - [x] cogs5e.charGen
    - [x] cogs5e.gametrack
    - [x] cogs5e.homebrew
    - [x] cogs5e.initTracker
    - [x] cogs5e.lookup
    - [x] cogs5e.pbpUtils
    - [x] cogs5e.sheetManager
    - [x] cogsmisc.customization
- [x] redo checks system
    - [x] use builtin or migrate checks.py?
- [x] rewrite bot prefix system
    - [x] main command prefix check
    - [x] alias handling
- [x] rewrite help system
- [x] change all server references to guild
- [x] check all privateChannel checks
- [x] remove no_pm param
- [x] remove all pass_context

**Comment by herrGagen** [comment]
Changes made (in discord.py) after commit 3f06f24 keep avrae from working. All of the Cog system changes keep the bot.add_cog(...) commands from working in the avrae/cogs5e/*.py files
