### ISSUE TITLE
AVR-458 Eldritch Blast not getting bonus CHA damage from Agonizing Blast

### ISSUE THREAD

**Issue by jerclarke** [avrae/avrae#909]
**Describe the bug**

When I `!cast Eldritch Blast` everything works well except that I have the "Eldritch Invocation" "Agonizing Blast", and it's extra damage isn't getting added to the blasts. 

Here's what D&D Beyond shows in my character sheet:

> Agonizing BlastPHB110
> When you cast eldritch blast, add +4 to the damage it deals on a hit.

Here's what Avrae outputs:

> Meta
> To Hit: 1d20 (10) + 7 = 17
> Damage: 1d10 (3) [force] = 3

It would be really cool if it took Agonizing Blast into account and added my CHA modifier. 

I guess the solution for me now will be something like `alias eblast=!cast Eldritch Blast -d 4` but I suspect a lot of people would forget to do this and miss out on their damage. 

**Severity**
Medium. Not the end of the world but would be a nice quality of life improvement for warlocks, almost all of whom will be relying on Agonizing Blast :)

**Context**
`!cast Eldritch Blast` when you have "Agonizing Blast" Eldritch invocation

**To Reproduce**
1. Create warlock with Agonizing Blast invocation
2. !cast Eldritch Blast
3. Review damage: CHA modifier isn't applied

**Expected behavior**
CHA modifier is applied to Eldritch Blast damage when you have Agonizing Blast.

Maybe some text is also output in the Effect section, explaining the bonus, or maybe not (it would just be noise most of the time)

**Screenshots**

<img width="637" alt="Screen Shot 2019-11-17 at 22 48 22 PM" src="https://user-images.githubusercontent.com/139995/69025421-89314380-098c-11ea-97c3-40ebd276bf40.png">
<img width="574" alt="Screen Shot 2019-11-17 at 22 47 04 PM" src="https://user-images.githubusercontent.com/139995/69025427-8f272480-098c-11ea-87e4-900655ad255a.png">

**Additional context**
Thank you for this amazing tool! Can't believe how fun it is rolling together in Discord!!!

**Comment by Croebh** [comment]
Unfortunately, Avrae doesn't actually track features like this, and she uses her own internal database for spells, looking only at the spell name to figure out which ones.

Our current best work around is to make a homebrew 'Agonizing Blast' spell in Avrae, and cast that. Alternatively, you could make a simple snippet (`!snippet ab -d {charismaMod}`) and use it whenever you cast (`!cast "Eldritch Blast" AB -t target1`)

**Comment by Infinidoge** [comment]
A tip for the snippet if you want to be a bit lazy, name the snippet `Blast` and cast the spell without quotes, it should cast just fine and apply the Blast snippet. Be careful in that this may cause issues if you have other spells named Eldritch X, as it will bring up the selection prompt for not being specific.

**Comment by jerclarke** [comment]
Hey all, thanks for the super fast replies!

> Unfortunately, Avrae doesn't actually track features like this, and she uses her own internal database for spells, looking only at the spell name to figure out which ones.

Ok, so there's no way to add this modifier into the default behavior I guess. That's too bad. 

At least this ticket will be here for anyone who searches in the future. 

FWIW here's the alias I will probably keep using, 

```
!alias eblast !cast "Eldritch Blast" -d {charismaMod}
```

It worked fine, allowed further arguments like `adv` and `-rr 2`, and seems like the simplest approach to me.

**Comment by mommothazaz123** [comment]
Looks like you've got a solution, but in summary for anyone who stumbles on this issue, there are four workarounds for this:

1. Create a [homebrew spell](https://avrae.io/dashboard/homebrew/spells) named Agonizing Blast that includes the additional damage.
2. Create an [attack](https://avrae.io/dashboard/characters) named Agonizing Blast, then use `!attack` instead of `!cast`. (`!a add "Agonizing Blast" -d "1d10+{charismaMod}[force]" -b charismaMod+proficiencyBonus`)
3. Create a snippet to add damage equal to your charisma mod (e.g. `!snippet agon -d {charismaMod}`)
4. Create an alias to cast Eldritch Blast that includes the damage (e.g. `!alias eblast cast "Eldritch Blast" -d {charismaMod}`)

**Comment by DrEVILish** [comment]
This isn't closed, as this is still a bug in Avrae.

Agonizing Blast should be automatically calculated and added in.

**Comment by Infinidoge** [comment]
Avrae does not import class features and thus does not pull in any information which would let it innately automate Agonizing Blast
